export const stocksHeaders = [
  "index",
  "currentPrice",
  "previousClose",
  "open",
  "percentChange",
  "fifty_Two_Weeks_high",
  "fifty_Two_Weeks_low",
];

export const stocksData = [
  {
    index: "Nifty 50 Index",
    currentPrice: 24302.15,
    previousClose: 24286.5,
    open: 24369.95,
    percentChange: -0.19,
    fifty_Two_Weeks_high: 24401,
    fifty_Two_Weeks_low: 18837.85,
  },
  {
    index: "Nifty Next 50 Index",
    currentPrice: 72928.25,
    previousClose: 72584.95,
    open: 72877.2,
    percentChange: 0.61,
    fifty_Two_Weeks_high: 73131.8,
    fifty_Two_Weeks_low: 42539.15,
  },
  {
    index: "Nifty Bank Index",
    currentPrice: 53103.7,
    previousClose: 53089.25,
    open: 53357.7,
    percentChange: -1.12,
    fifty_Two_Weeks_high: 53357.7,
    fifty_Two_Weeks_low: 42105.4,
  },
  {
    index: "Nifty PSU Bank Index",
    currentPrice: 7266,
    previousClose: 7254.2,
    open: 7284.05,
    percentChange: 0.81,
    fifty_Two_Weeks_high: 8053.3,
    fifty_Two_Weeks_low: 4331.6,
  },
  {
    index: "Nifty Financial Services Index",
    currentPrice: 23879.7,
    previousClose: 23923.75,
    open: 24044.25,
    percentChange: -1.3,
    fifty_Two_Weeks_high: 24046.6,
    fifty_Two_Weeks_low: 18870.15,
  },
  {
    index: "Nifty FMCG Index",
    currentPrice: 57058.4,
    previousClose: 57177.55,
    open: 57325.7,
    percentChange: 0.86,
    fifty_Two_Weeks_high: 58832.65,
    fifty_Two_Weeks_low: 50607,
  },
  {
    index: "Nifty IT Index",
    currentPrice: 37725.9,
    previousClose: 37314.35,
    open: 37455.65,
    percentChange: 0.06,
    fifty_Two_Weeks_high: 38559.85,
    fifty_Two_Weeks_low: 29020.2,
  },
  {
    index: "Nifty Pharma Index",
    currentPrice: 20192.6,
    previousClose: 19915.3,
    open: 19955.7,
    percentChange: 1.28,
    fifty_Two_Weeks_high: 20238.6,
    fifty_Two_Weeks_low: 13705.35,
  },
];

export const gainersHeading = ["SECURITIES", "percentChange"];
export const gainersData = [
  { SECURITIES: "TATAMOTORS", percentChange: 2.75 },
  { SECURITIES: "HCLTECH", percentChange: 2.63 },
  { SECURITIES: "ICICIBANK", percentChange: 2.53 },
  { SECURITIES: "SUNPHARMA", percentChange: 1.83 },
  { SECURITIES: "TCS", percentChange: 1.38 },
  { SECURITIES: "INFY", percentChange: 1.32 },
  { SECURITIES: "HDFCLIFE", percentChange: 1.28 },
  { SECURITIES: "KOTAKBANK", percentChange: 1.18 },
  { SECURITIES: "COALINDIA", percentChange: 1.02 },
  { SECURITIES: "ONGC", percentChange: 1.02 },
];
export const bankData = [
  { SECURITIES: "ICICIBANK", percentChange: 2.53 },
  { SECURITIES: "AUBANK", percentChange: 1.64 },
  { SECURITIES: "KOTAKBANK", percentChange: 1.18 },
  { SECURITIES: "BANKBARODA", percentChange: 0.69 },
  { SECURITIES: "IDFCFIRSTB", percentChange: 0.31 },
  { SECURITIES: "PNB", percentChange: 0.04 },
  { SECURITIES: "FEDERALBNK", percentChange: -0.14 },
  { SECURITIES: "AXISBANK", percentChange: -0.17 },
  { SECURITIES: "SBIN", percentChange: -0.17 },
  { SECURITIES: "INDUSINDBK", percentChange: -0.77 },
  { SECURITIES: "BANDHANBNK", percentChange: -1.77 },
  { SECURITIES: "HDFCBANK", percentChange: -2.3 },
];

export const serviceData = [
  { SECURITIES: "ICICIBANK", percentChange: 2.53 },
  { SECURITIES: "HDFCAMC", percentChange: 2.52 },
  { SECURITIES: "RECLTD", percentChange: 2.44 },
  { SECURITIES: "HDFCLIFE", percentChange: 1.28 },
  { SECURITIES: "KOTAKBANK", percentChange: 1.18 },
  { SECURITIES: "MUTHOOTFIN", percentChange: 1 },
  { SECURITIES: "IDFC", percentChange: 0.86 },
  { SECURITIES: "SBILIFE", percentChange: 0.65 },
  { SECURITIES: "SBICARD", percentChange: 0.6 },
  { SECURITIES: "PFC", percentChange: 0.56 },
];
export const indexHeaders = [
  "index",
  "currentPrice",
  "previousClose",
  "open",
  "percentChange",
  "fifty_Two_Weeks_high",
  "fifty_Two_Weeks_low",
];
export const indexData = [
  {
    index: "Nifty 50 Index",
    currentPrice: 24323.85,
    previousClose: 24302.15,
    open: 24213.35,
    percentChange: "0.09%",
    fifty_Two_Weeks_high: 24401,
    fifty_Two_Weeks_low: 18837.85,
  },
  {
    index: "Nifty Next 50 Index",
    currentPrice: 73426.55,
    previousClose: 72928.25,
    open: 72984.85,
    percentChange: "0.68%",
    fifty_Two_Weeks_high: 73483.8,
    fifty_Two_Weeks_low: 42539.15,
  },
  {
    index: "Nifty Bank Index",
    currentPrice: 52660.35,
    previousClose: 53103.7,
    open: 52560.1,
    percentChange: "-0.83%",
    fifty_Two_Weeks_high: 53357.7,
    fifty_Two_Weeks_low: 42105.4,
  },
  {
    index: "Nifty PSU Bank Index",
    currentPrice: 7356.75,
    previousClose: 7266,
    open: 7267.8,
    percentChange: "1.25%",
    fifty_Two_Weeks_high: 8053.3,
    fifty_Two_Weeks_low: 4331.6,
  },
  {
    index: "Nifty Financial Services Index",
    currentPrice: 23641.75,
    previousClose: 23879.7,
    open: 23640.4,
    percentChange: "-1.00%",
    fifty_Two_Weeks_high: 24046.6,
    fifty_Two_Weeks_low: 18870.15,
  },
  {
    index: "Nifty FMCG Index",
    currentPrice: 57673,
    previousClose: 57058.4,
    open: 57102.35,
    percentChange: "1.08%",
    fifty_Two_Weeks_high: 58832.65,
    fifty_Two_Weeks_low: 50607,
  },
  {
    index: "Nifty IT Index",
    currentPrice: 37720.75,
    previousClose: 37725.9,
    open: 37754.15,
    percentChange: "-0.01%",
    fifty_Two_Weeks_high: 38559.85,
    fifty_Two_Weeks_low: 29020.2,
  },
  {
    index: "Nifty Pharma Index",
    currentPrice: 20453.85,
    previousClose: 20192.6,
    open: 20237.5,
    percentChange: "1.29%",
    fifty_Two_Weeks_high: 20516.1,
    fifty_Two_Weeks_low: 13705.35,
  },
];
export const sensexHeaders = ["Symbol", "percentChange"];
export const sensexData = [
  { Symbol: "HCLTECH", percentChange: 2.85 },
  { Symbol: "ICICIBANK", percentChange: 2.65 },
  { Symbol: "TATAMOTORS", percentChange: 2.4 },
  { Symbol: "SUNPHARMA", percentChange: 1.66 },
  { Symbol: "TCS", percentChange: 1.42 },
  { Symbol: "INFY", percentChange: 1.32 },
  { Symbol: "KOTAKBANK", percentChange: 1.26 },
  { Symbol: "M&M", percentChange: 0.89 },
  { Symbol: "ASIANPAINT", percentChange: 0.57 },
  { Symbol: "BHARTIARTL", percentChange: 0.21 },
];
export const bankexHeaders = ["Symbol", "percentChange"];
export const bankexData = [
  { Symbol: "ICICIBANK", percentChange: 2.65 },
  { Symbol: "KOTAKBANK", percentChange: 1.26 },
  { Symbol: "BANKBARODA", percentChange: 0.9 },
  { Symbol: "CANBK", percentChange: 0.21 },
  { Symbol: "YESBANK", percentChange: 0.13 },
  { Symbol: "AXISBANK", percentChange: 0.04 },
  { Symbol: "HDFCBANK", percentChange: -2.36 },
  { Symbol: "INDUSINDBK", percentChange: -0.85 },
  { Symbol: "FEDERALBNK", percentChange: -0.3 },
  { Symbol: "SBIN", percentChange: -0.1 },
];
export const financial_serviceHeaders = ["Symbol", "percentChange"];
export const financial_serviceData = [
  { Symbol: "HUDCO", percentChange: 7.65 },
  { Symbol: "BAJAJHLDNG", percentChange: 6.5 },
  { Symbol: "UTKARSHBNK", percentChange: 5 },
  { Symbol: "NIACL", percentChange: 4.34 },
  { Symbol: "SHAREINDIA", percentChange: 3.5 },
  { Symbol: "MAHSCOOTER", percentChange: 3.4 },
  { Symbol: "INDIASHLTR", percentChange: 2.77 },
  { Symbol: "ICICIBANK", percentChange: 2.65 },
  { Symbol: "RECLTD", percentChange: 2.38 },
  { Symbol: "HDFCAMC", percentChange: 2.37 },
];
export const marketHeaders = [
  "indicators",
  "previous_Day",
  "current_Day",
  "change",
];
export const marketData = [
  { indicators: "Dow", previous_Day: 39332, current_Day: 39308, change: -0.06 },
  {
    indicators: "NASDAQ",
    previous_Day: 18029,
    current_Day: 18188,
    change: 0.88,
  },
  {
    indicators: "S & P 500",
    previous_Day: 5509,
    current_Day: 5537,
    change: 0.51,
  },
  {
    indicators: "Nikkei 225",
    previous_Day: 40075,
    current_Day: 40581,
    change: 1.26,
  },
  {
    indicators: "FTSE 100",
    previous_Day: 8121,
    current_Day: 8171,
    change: 0.61,
  },
  {
    indicators: "US 10-yr (%)",
    previous_Day: 4.44,
    current_Day: 4.35,
    change: -9,
  },
  {
    indicators: "US 2-yr (%)",
    previous_Day: 4.74,
    current_Day: 4.69,
    change: -5,
  },
  {
    indicators: "UK 10-yr (%)",
    previous_Day: 4.25,
    current_Day: 4.17,
    change: -8,
  },
  {
    indicators: "Germany 10-yr (%)",
    previous_Day: 2.61,
    current_Day: 2.56,
    change: -5,
  },
  {
    indicators: "Gold ($/t oz)",
    previous_Day: 2329,
    current_Day: 2356,
    change: 1.15,
  },
  {
    indicators: "Crude Oil-WTI ($/bbl)",
    previous_Day: 83.15,
    current_Day: 83.59,
    change: 0.53,
  },
  {
    indicators: "Crude Oil-Brent ($/bbl)",
    previous_Day: 86.58,
    current_Day: 87.07,
    change: 0.57,
  },
  { indicators: "€/$", previous_Day: 1.07, current_Day: 1.08, change: 0.39 },
  {
    indicators: "$/¥*",
    previous_Day: 161.44,
    current_Day: 161.68,
    change: 0.15,
  },
  { indicators: "£/$", previous_Day: 1.27, current_Day: 1.27, change: 0.44 },
];
export const liquidityHeaders = ["indicators", "previous_Day", "current_Day"];

export const liquidityData = [
  { indicators: "Avg. Call Rate (%)", previous_Day: 6.49, current_Day: 6.49 },
  {
    indicators: "Vol. Traded (Rs million)",
    previous_Day: 122335,
    current_Day: 121198,
  },
  {
    indicators: "Net banking system liquidity outstanding (Rs million) *",
    previous_Day: -912253,
    current_Day: -1250449,
  },
  { indicators: "T-Bills 91 days (%)", previous_Day: 6.72, current_Day: 6.76 },
  { indicators: "182 days (%)", previous_Day: 6.89, current_Day: 6.89 },
  { indicators: "364 days (%)", previous_Day: 6.93, current_Day: 6.94 },
  { indicators: "G-sec 3 years (%)", previous_Day: 6.97, current_Day: 6.96 },
  { indicators: "5 years (%)", previous_Day: 7.03, current_Day: 7.0 },
  { indicators: "10 years (%)", previous_Day: 7.01, current_Day: 7.0 },
];
export const marketChangeHeaders = [
  "indicators",
  "previous_Day",
  "current_Day",
  "change",
];

export const marketChangeData = [
  {
    indicators: "Sensex",
    previous_Day: 79441,
    current_Day: 79987,
    change: 0.69,
  },
  {
    indicators: "NIFTY",
    previous_Day: 24124,
    current_Day: 24287,
    change: 0.67,
  },
  {
    indicators: "$/Rs*",
    previous_Day: 83.51,
    current_Day: 83.54,
    change: 0.03,
  },
  { indicators: "€/Rs*", previous_Day: 89.7, current_Day: 90.08, change: 0.42 },
];
