export const employeeHeaders = [
  "id",
  "image",
  "firstName",
  "lastName",
  "email",
  "contactNumber",
  "age",
  "dob",
  "salary",
  "address",
];

export const employeeData = [
  {
    id: 1001,
    image: "https://hub.dummyapis.com/Image?text=JK&height=120&width=120",
    firstName: "Judy",
    lastName: "King",
    email: "Judy.King@dummyapis.com",
    contactNumber: "4466199460",
    age: 44,
    dob: "16/06/1980",
    salary: 1,
    address: "Address1",
  },
  {
    id: 1002,
    image: "https://hub.dummyapis.com/Image?text=FC&height=120&width=120",
    firstName: "Friedrich",
    lastName: "Collins",
    email: "Friedrich.Collins@dummyapis.com",
    contactNumber: "4107995796",
    age: 32,
    dob: "26/01/1992",
    salary: 2,
    address: "Address2",
  },
  {
    id: 1003,
    image: "https://hub.dummyapis.com/Image?text=MS&height=120&width=120",
    firstName: "Miguel",
    lastName: "Shanahan",
    email: "Miguel.Shanahan@dummyapis.com",
    contactNumber: "4621697539",
    age: 67,
    dob: "06/04/1957",
    salary: 3,
    address: "Address3",
  },
  {
    id: 1004,
    image: "https://hub.dummyapis.com/Image?text=LF&height=120&width=120",
    firstName: "Lauryn",
    lastName: "Fisher",
    email: "Lauryn.Fisher@dummyapis.com",
    contactNumber: "4848899507",
    age: 35,
    dob: "10/11/1989",
    salary: 4,
    address: "Address4",
  },
  {
    id: 1005,
    image: "https://hub.dummyapis.com/Image?text=SG&height=120&width=120",
    firstName: "Syble",
    lastName: "Grant",
    email: "Syble.Grant@dummyapis.com",
    contactNumber: "4450595357",
    age: 80,
    dob: "16/12/1944",
    salary: 5,
    address: "Address5",
  },
  {
    id: 1006,
    image: "https://hub.dummyapis.com/Image?text=GM&height=120&width=120",
    firstName: "Gunnar",
    lastName: "Murray",
    email: "Gunnar.Murray@dummyapis.com",
    contactNumber: "4741395735",
    age: 80,
    dob: "21/08/1944",
    salary: 6,
    address: "Address6",
  },
  {
    id: 1007,
    image: "https://hub.dummyapis.com/Image?text=NG&height=120&width=120",
    firstName: "Nicklaus",
    lastName: "Grady",
    email: "Nicklaus.Grady@dummyapis.com",
    contactNumber: "4095999488",
    age: 87,
    dob: "08/10/1937",
    salary: 7,
    address: "Address7",
  },
  {
    id: 1008,
    image: "https://hub.dummyapis.com/Image?text=HB&height=120&width=120",
    firstName: "Harvey",
    lastName: "Bruen",
    email: "Harvey.Bruen@dummyapis.com",
    contactNumber: "4058893906",
    age: 40,
    dob: "06/11/1984",
    salary: 8,
    address: "Address8",
  },
  {
    id: 1009,
    image: "https://hub.dummyapis.com/Image?text=CM&height=120&width=120",
    firstName: "Colin",
    lastName: "Mayer",
    email: "Colin.Mayer@dummyapis.com",
    contactNumber: "4509197735",
    age: 29,
    dob: "26/05/1995",
    salary: 9,
    address: "Address9",
  },
  {
    id: 1010,
    image: "https://hub.dummyapis.com/Image?text=CS&height=120&width=120",
    firstName: "Clovis",
    lastName: "Stanton",
    email: "Clovis.Stanton@dummyapis.com",
    contactNumber: "4693195831",
    age: 85,
    dob: "09/10/1939",
    salary: 10,
    address: "Address10",
  },
];
